### ISSUE TITLE
Fixtures generation broke

### ISSUE THREAD

**Issue by ishakir** [ishakir/shakitz-fantasy-football#57]
I, [2015-08-12T18:07:52.040294 #2454]  INFO -- : Completed 200 OK in 738ms (Views: 44.3ms | ActiveRecord: 69.1ms)
{ 36634480 rufus-scheduler intercepted an error:
  36634480   job:
  36634480     Rufus::Scheduler::AtJob "2015/08/13 00:00:00" {:no_error=>true, :_t=>2015-08-13 00:00:00 -0400}
  36634480   error:
  36634480     36634480
  36634480     NameError
  36634480     uninitialized constant FixtureGenerator
  36634480       /home/rails/config/initializers/schedule_fixtures_generation.rb:17:in `block in <top (required)>'
  36634480       /home/rails/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `call'
  36634480       /home/rails/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  36634480       /home/rails/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:258:in `do

**Comment by ishakir** [comment]
11503780     undefined local variable or method `kind' for main:Object
  11503780       /home/rails/config/initializers/schedule_stats_updates.rb:38:in `block (3 levels) in <top (required)>'
  11503780       /home/rails/lib/shakitz_scheduler.rb:16:in `block in at'
  11503780       /home/rails/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `call'
  11503780       /home/rails/vendor/bundle/ruby/2.1
