### ISSUE TITLE
Application does not work on Ruby v2.2.+

### ISSUE THREAD

**Issue by MikeSpitz** [ishakir/shakitz-fantasy-football#59]
Returns following error:

app/models/with_game_week.rb:40:in `start_of_first_gameweek'
app/models/with_game_week.rb:58:in `current_game_week'
app/controllers/user_controller.rb:31:in `home'

**Comment by ishakir** [comment]
Make sure we re-enable the travis job when we fix this

**Comment by ishakir** [comment]
Also entertain the idea that this might work on the latest version of ruby 2.2
